# Generated by Django 3.1.4 on 2020-12-19 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pid', models.CharField(default='', max_length=250)),
                ('url', models.CharField(default='', max_length=250)),
                ('brand', models.CharField(default='', max_length=250)),
                ('title', models.CharField(default='', max_length=250)),
                ('price', models.FloatField(default=0.0)),
                ('width', models.FloatField(default=0.0)),
                ('height', models.FloatField(default=0.0)),
                ('length', models.FloatField(default=0.0)),
                ('weight', models.FloatField(default=0.0)),
                ('delivery_availability', models.CharField(default='', max_length=250)),
            ],
        ),
    ]
