# Generated by Django 3.1.4 on 2020-12-19 10:43

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('view_cntr', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='dailyViewCount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=datetime.datetime.now)),
                ('count', models.IntegerField(default=0)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='view_cntr.product')),
            ],
        ),
    ]
